const Discord = require('discord.js');

exports.run = (client, message, args) => {
	let mesaj = args.slice(0).join(' ');
    var responses = [
        "**Yatağımın altında birşey var!** \nHer çocuk gibi o da dolabın içinde saklanan yaratıklardan, yatağın altındaki canavarlardan korkuyordu. Bu nedenle de kapısını hiç kapatmaz, her gece uykuya dalana kadar annesi ya da babasının anlattığı masalları dinlerdi. Yine bir gün babasına uykusunun geldiğini söyledi ve beraber çocuğun odasına gittiler. Çocuk pijamalarını giyerken, babası bu sırada çalan telefona koştu ama ahizeden sadece cızırtı geliyordu. \nHatlarda bir sorun olduğunu düşünerek, oğlunun yanına geri dönen baba, onun yatağına çoktan girmiş olduğunu gördü. Ve her gece yaptığı gibi “hadi bakalım, yatağının altında canavar var mı yok mu kontrol edelim” dedi. Ama aşağıya eğilince orada öylece donakalacaktı. Çünkü yatağın altında elindeki pijamalarına sıkı sıkı sarılmış oğlu vardı ve korku içinde fısıldayarak “baba yatağımın üstünde biri var” diyordu. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-yatagimin-ustunde-biri-var.gif",
		"**Hayalet Anne** \nKardeşim ve ben küçükken, ailemizle sevimli bir çiftlik evine taşınmıştık. Babamın işi gereği, 7-8 ay boyunca orada kalacaktık. Ama bu bizim için hiç sorun değildi çünkü hem ben hem de kardeşim o evde oynamayı çok seviyorduk. Dışarıda yemyeşil kocaman bir alan vardı. Ayrıca ev de bir sürü eski eşyayla, zaman geçirecek onlarca ıvır zıvırla doluydu. Tüm bunların yanı sıra, evin en sevdiğimiz tarafı oradaki kibar hayaletti. Kardeşimle ben, kibarlığı ve şefkati nedeniyle ona Anne ismini vermiştik. \nAnne bizi fazlasıyla düşünüyor olmalıydı çünkü sabah uyandığımızda komodinlerimizin üzerinde hep birer bardak süt oluyordu. Ayrıca biz oyun oynarken ya da televizyon izlerken, salondaki eski sandalyeye oturup bizi seyrediyor, hatta bazen sandalyeyi odanın ortasına kadar getiriyordu. Anne her anımızda yanımızda oluyor, bizi koruyup kolluyordu. Ya da biz öyle sanıyorduk. Aradan yıllar geçtikten sonra, eski bir gazetede tesadüfen bizim kaldığımız çiftlik evinin fotoğrafını gördüm ve haberi okumaya başladım. \nAnne dediğimiz kadının fotoğrafının altında yazanlar, onun dul bir kadın olduğunu, 2 çocuğunu sütün içine zehir koyarak öldürdüğünü ve sonrasında da salonun ortasında kendini asarak intihar ettiğini gösteriyordu. Ve fotoğrafa bakılırsa; kadının kendini öldürmek için üstüne çıktığı sandalye, biz oyun oynarken onun oturup bizi izlediği sandalyeydi. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-hayalet-anne.gif",
		"**Şakacı Hayalet** \nGeçtiğimiz yıl, arkadaşlarımın ısrarları sonucunda bir barın açılışına gitmiştim. Biraz oturup eğlendikten sonra, kız arkadaşımı aramak için elimi cebime attım. Ama telefonum cebimde değildi! Masada ya da yerlerde falan da yoktu. Telefonumu bulabilmek için arkadaşımdan kendi numaramı aradım. Birkaç kez çaldıktan sonra telefon açıldı ve kiminle görüştüğümü sordum. \nAma duyduğum tek şey rahatsız edici bir kıkırdama sesiydi. Sonra yeniden arasam da açan olmadı. Ben de telefonumu düşürdüğümü ve çocukların eline geçtiğini düşünerek ümidi kestim. Gece yarısını geçerken eve döndüm ve tam yatağa girmek üzereyken gördüğüm manzara karşısında aklımdan şüphe ettim. Çünkü telefonum yatağımın tam üzerinde, yani evden çıkarken bıraktığım yerde duruyordu. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-sakaci-ruh.gif",
		"**İnsanlarda yapabilir!** \nAnne ve babasının iş seyahatleri yüzünden sık sık tek başına kalan genç kızın tek arkadaşı sadık köpeğiymiş. Hem bir koruyucu hem de bir arkadaş olan köpeği sayesinde genç kız rahatlıkla uyuyabiliyor, yalnız kaldığı gecelerde kendini güvende hissediyormuş. Yine ailesinin şehir dışında olduğu bir gecede aniden uyanan kız, musluklardan birinin akıttığını düşünerek aşağıya inmiş. Tüm muslukları kapattıktan sonra yatağına geri dönmüş ve köpeği elini yalamış. \nKısa süre sonra musluğun hala akıttığını fark eden kız, bu kez evdeki bütün muslukları bir bir kontrol ederek odasına geri dönmüş. Kolunu aşağıya doğru sarkıtmış ve köpeği elini yalamış. Ama o sinir bozucu su damlama sesi hala varmış. Uykusu iyice açılan genç kız, sesin epey yakınından, kendi banyosundan geldiğini fark etmiş. Kapıyı açtığında ise tavandan sarkan boğazı kesilmiş köpeğiyle karşılaşmış. Ancak yaşayacağı en büyük şok değilmiş çünkü aynada köpeğinin kanıyla yazılmış şu sözler varmış: “İnsanlar da yalayabilir.” https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-insanlar-da-yapabilir.gif",
		"**Arkadaki kim?** \nKadın, geç saatlere kadar arkadaşlarıyla eğlenmiş ve eve dönmek için arabasına binmişti. Biraz ilerledikten sonra, onu takip eden bir araba olduğunu fark etti. Ama panik yapmamak için onun da kendisiyle aynı istikamete gidebileceğini düşünerek rahatlamaya çalıştı. Aradan dakikalar geçmesine rağmen, araba tam arkasından geliyor, hızını kadına göre ayarlıyordu. Sonunda araba iyice yaklaştı ve arka arkaya selektör yapmaya başladı. \nİyice korkan kadın, bir an önce eve gidip polisi aramak için gaza bastı. Fakat arkadaki araba hala selektör yapıyor, kadını yakalamaya çalışıyordu. Sonunda evinin önüne gelen kadın arabadan indi ve evine doğru koşarken arkasındaki arabanın şoförünün de aracından indiğini gördü. Adamın bağırarak bir şeyler söylediğini duysa da ne dediğini anlamadan evine girdi ve polisi aradı. Polis geldiğinde ise gerçekler ortaya çıktı. Meğer gerçek tehlike kadını takip eden araba değil, kadının arabasının arka koltuğunda saklanan kişiymiş. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-arkadaki-kim.gif",
		"**Amen-Ra'ın Laneti** \n1880’li yıllarda Güney Mısır’da Amen-Ra’nın mumyasını bulan 4 İngiliz genci yüzünden başlamış felaketler zinciri. Önce gençlerden bir tanesi tuhaf biçimde ortadan kaybolmuş. Sonrasında bir diğeri, hizmetkarı tarafından vurularak öldürülmüş. Ve cinayetin ardından hizmetkar bunu istemeyerek yaptığını itiraf etmiş. Geriye kalan 2 İngiliz genç, mumyayı alıp İngiltere’ye dönmüşler. Bir tanesi parasını yatırdığı bankanın battığını öğrenirken, diğeri de ölümcül bir hastalığa yakalanarak bütün servetini sokaklarda harcamış. \nBir iş adamının eline geçen lanetli prensesin mumyası, British Museum’a hediye edilmiş. Ama garip olaylar devam ediyormuş. Müzede çalışan bekçiler, tabuttan ağlama sesleri duyduklarını söylüyor, ona yaklaşmaktan korkuyorlarmış. Aradan çok fazla zaman geçmeden, bekçilerden biri müzede ölü bulunmuş. Bu sırada mumyanın fotoğrafını çeken bir gazeteci de kendini vurarak öldürmüş. Aradan yıllar geçtikten sonra Amerikalı bir arkeolog tarafından satın alınan mumya, 1912 yılında Titanik’e yüklenmiş. Ve hepimizin bildiği gibi, batmaz denilen Titanik bir buz dağına çarparak yüzlerce insanın mezarı olmuş. Amen-Ra’nın lanetiyle ilgili son olay da bu olmuş. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-amen-ra-laneti.gif",
		"**Tuhaf Tablolar** \nİki arkadaş, birlikte kamp yapmak için yola çıkarlar. Fakat karanlık çökmeden kısa süre önce arabaları bozulur. Yardım aramak için dışarı çıksalar da orman yolundan kimse geçmez. Bir müddet yürüyen gençler, ağaçların arkasında bir ev olduğunu görür ve evin kapısını çalarlar. Ama etrafta ne bir ses, ne de bir hayat belirtisi vardır. Arka kapıdan eve giren arkadaşlar, telefon bulmak ümidiyle etrafa baksalar da çabaları boşunadır. Zaten karanlıktan pek bir şey de göremezler. \nSonunda iyice yorulur ve orada uyumaya karar verirler. Bir battaniyenin altına girip birlikte yatan gençler, duvarlarda asılı tuhaf tablolardan dolayı uzun süre uyuyamazlar. Çünkü hepsi garip şekilde onlara bakıyor gibidir. Ayrıca görünüşleri de epey korkunçtur. Tablolara baka baka korkuyla uyuyakalan gençler, ertesi gün yüzlerine vuran güneş ışınlarıyla uyanırlar. Ve yataktan kalktıktan kısa süre sonra etrafa dehşetle bakarlar. Çünkü duvarlarda gece onları rahatsız eden tablolar, aslında tablo değil, birkaç küçük camdır. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-tuhaf-tablolar.gif",
		"**Adını söylemeye korktuğum şey** \nAdımı 3 kere duymama rağmen etrafımda kimsecikler yoktu. Birkaç saat sonra uykumdan aniden uyandığımdaysa tarif edemediğim o şey, yatağımın başında oturmuş bana bakıyordu. https://img.paratic.com/dosya/2017/06/kisa-korku-hikayeleri-adini-soylemeye-korktugum-sey.gif",
		"**Peşimdeki Gölge!** \nSimsiyah bir gölge olarak tanımlamasam da onu tarif etmek imkansız. Aylarca peşimi bırakmayan tuhaf varlık, bana hayatımın en kötü günlerini yaşattı. https://img.paratic.com/dosya/2017/06/kisa-korku-hikayeleri-pesimdeki-golge.gif",
		"**Farklı Suretlerde Görünen Varlık!** \nAnnemin evde olduğunu biliyordum. Bilmediğim şeyse yolun karşısında gördüğüm anneme tıpatıp benzeyen kadının benden ne istediğiydi. https://img.paratic.com/dosya/2017/06/kisa-korku-hikayeleri-farkli-suretlerde-gorunen-varlik.gif",
		"**Odamın Köşesinde Oturuyordu!** \nOnu odamın duvar dibinde otururken görebiliyordum. Kan ter içerisinde uyanıyor ve tam kabusmuş diyerek rahatlayacakken, aynı yerden bana bakıyordu. Gözlerimi kapayıp dilim döndüğünce dua ettiğimdeyse, nihayet yok oluyordu. https://img.paratic.com/dosya/2017/06/kisa-korku-hikayeleri-odamin-kosesinde-oturuyordu.gif",
		"**Anne Ninnisi** \nBaba, yeni kalkmış, yatağında tembellik yapıyordu. Anne ise mutfakta kahvaltı hazırlıyordu. Alt kattan gelen sesleri duyarak biraz daha dinlenmek için uyumaya devam eden baba, bir müddet sonra aniden gözlerini açtı. Belli ki karısı, kısa süre önce dünyaya gelen bebeklerine ninni söylüyordu. Monitöre baktığında bebeğin mışıl mışıl uyuduğunu, annenin de ninni söylemeye devam ettiğini gördü. \nKalkıp giyindi ve tam onların yanına gidecekken, aşağıdan gelen kapı sesine doğru yöneldi. Gelen, büyük çocukları olmalıydı. Onu karşılamak için merdivenlere doğru yürüdü ve gördüğü manzara karşısında öylece kalakaldı. Çünkü kapıdan giren kişi, dakikalardır bebeğin odasında ninni söylediğini düşündüğü karısıydı ve belli ki uzun süredir evde değildi. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-anne-ninnisi.gif",
		"**Bodrumdaki kim?** \nBodrum kata girmek yasaktı. Bu her zaman böyle olmuştu. Ve çocuk, annesinin koyduğu yasağı çiğnememek için direniyordu. Çünkü o annesinin sözünden hiçbir zaman çıkmazdı. Ama bir gün, bodrumdan gelen seslere daha fazla karşı koyamadı ve aşağıya inmeye karar verdi. Sonuçta; annesi dışarıda çim biçmekle meşguldü ve o da bu sırada bodrumdaki küçük köpekle birazcık oynayabilirdi. Hem belki de çok açtı köpek. Sonuçta; günlerdir ağlar gibi havlıyordu. Yanına biraz da süt alarak bodrum kata inmeye başladı ve kilitli kapıyı açtı. \nAşağısı çok karanlıktı ve köpeğin hiç sesi çıkmıyordu. İçeri doğru biraz daha ilerlediğinde, gözleri karanlığa alışmış, etraftaki cisimleri seçmeye başlamıştı. Nefesini tutmuş, çevresine bakmaya devam ederken, bir çift el onu arkadan sımsıkı tuttu ve dışarı çıkardı. Ne olduğunu anlayamayan çocuk, karşısında ona öfkeyle bakan annesini gördü. Çok kızgın olan ve ona ilk kez bağıran annesine bir daha oraya inmeyeceğine söz vererek odasına çıktı. Ve bir daha annesini sinirlendirmemek için ne duyduğu köpek seslerinden ne de bodrumdaki elleri ve ayakları olmayan çocuktan söz edebildi. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-bodrumdaki-kim.gif",
		"**Rus Uyku Deneyi – Kesmeye Devam Et** \nDenekler, II. Dünya Savaşı sırasında yakalanmış siyasi tutsaklardı. Ve deneye başlamadan önce, onlara 30 günün sonunda hayatta kalan kişinin özgür bırakılacağı söylenmişti. Deneyin amacı ise; bir insanın ne kadar süre uykusuz kalabileceği ve bunun insan üzerinde nasıl etkiler yapacağını belirlemekti. Odada 5 kişiye 1 ay boyunca yetecek yiyecek ve su bulunuyordu. Ayrıca deneklerin uyumamaları için odaya sürekli uyarıcı gaz ve oksijen veriliyordu. İlk 5 gün her şey yolunda gitse de sonrasında işler değişecekti. \nMahkumlar birbirleriyle konuşmayı keserek, mikrofonlara fısıldamaya başladılar. 9 günden sonra bir denek çığlık atmaya başladı ve saatlerce bağırmaya devam etti. Ardında ikinci deneğin çığlıkları duyuldu. Diğer 3 denek ise mikrofonlara fısıldayarak, küçük gözlem camlarını kitap sayfalarıyla kapattılar. Sonrasında çığlıklar tamamen kesildi. Bu sessizlik günlerce sürdü. Nihayet araştırmacılar, ne olup bittiğini görmek için odaya girmeye karar verdiklerinde, içeriden “artık özgür olmak istemiyoruz” cevabını aldılar. \nDeneyi bitirme kararı alan yetkililer, içeri girdiklerinde korkunç bir manzarayla karşılaştılar. Deneklerden biri ölmüş, zemin kana dolmuş, yiyeceklere neredeyse hiç dokunulmamış, diğerleri ise deyim yerindeyse insanlıktan çıkmışlardı. Derileri paramparça olan deneklerin, iç organları gözüküyordu. Şoku atlatan yetkililer, denekleri dışarıya çıkartmaya çalışsa da onlar bunu istemiyordu. İşte bu mücadele sırasında, askerlerden ve deneklerden biri ölürken, bir diğer askerin de testisleri koparıldı. Sağ kalan 3 denek, tıbbi merkezlere kaldırılıp tedavi edilmeye çalışıldı. Fakat hepsi de uyanık kalmak istiyor, daha fazla uyarıcı gaz almak için ısrar ediyordu. \nDeneklerden bir tanesi verilen anesteziyle günler sonra uykuya daldı ve bir daha uyanamadı. Bir diğer denek ise ameliyat sırasında birkaç kez gülümsedi ve hemşirelerden biri onun “kesmeye devam et” dediğini duydu. Tüm bu olanlara rağmen askeri yetkili, araştırmacılara 2 deneğin yeniden odaya kapatılmasını hapsetti ve bu emri üzerine emri verdiği araştırmacı tarafından vuruldu. Bu deneyin amacını çoktan aştığını düşünen araştırmacı, daha sonra da denekleri öldürdü. Ama hala konuşabilen deneği öldürmeden önce ona, ne olduğunu sormayı da ihmal etmedi. Denekten aldığı “Bu kadar kolay mı unuttunuz? Biz sizleriz…” ile başlayan cevabı ise en az kendisi kadar korkutucuydu. https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-rus-uyku-deneyi-kesmeye-devam-et.gif",
		"**Sadece kırmızı** \nYeni bir iş görüşmesi için şehir dışına gidiyordum. Uzun süredir beş parasızdım ve bu işi alırsam hayatımı yeniden yoluna koyabilirdim. Saatlerce araba kullandıktan sonra, geceyi geçirmek için yol kenarındaki bir motele girdim. Resepsiyondaki tuhaf kadına bir oda istediğimi söyledikten sonra anahtarımı alarak merdivenlere doğru yürüdüm. Tam bu sırada kadın “Son bir şey daha beyefendi! Otelde numarasız ve her zaman kilitli olan bir oda var. Oraya yaklaşmamanızı öneririm.” dedi. Çatlak kadının söylediklerini umursamayarak odaya çıktım ve yatağa uzandım. Ama birkaç saat sonra rahatsız edici bir su sesiyle uyandım. \nYeniden uyumaya çalışsam da durmak bilmeyen ses buna engel oluyordu. Ben de odanın kapısını açıp, musluğu açık unutan kimse onu bulmak için koridora çıktım. Çok geçmeden su sesinin karşıdaki odadan geldiğini anladım ve kapılarını çaldım. Her seferinde daha hızlı vursam da kapıyı açan kimse yoktu. Sonunda delikten bakmaya karar verdim ve gözümü kapı deliğine yaklaştırarak içeriyi görmeye çalıştım. Fakat gördüğüm tek şey kırmızıydı! Birileri kapı deliğine kırmızı bir örtü falan asmış olmalıydı. Sinirle aşağıya inip, resepsiyondaki kadına olanları anlattım. \nVe kadın beni sessizce dinledikten sonra, odanın hikayesini anlatmaya başladı. “Yıllar önce o odada bir kadın öldürüldü. Ve sadece kapıdan içeri giren genç bir adama baktığı için. Kıskanç kocasının gözü döndü ve kadına odalarına çıkmayı teklif etti. O kadar güzel ve naif bir kadındı ki! Gülümseyerek kocasının dediğini yaptı ve merdivenlerden yukarı çıktı. Sabah olduğunda çift aşağıya inmedi, öğlen ya da akşam da öyle. Sonunda anahtarımla odalarına girdiğimde banyodan dışarı taşan suyu gördüm. Banyonun kapısını açtığımda ise kadının bembeyaz teni ve oyulmuş, kırmızı gözleriyle karşılaştım” https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-sadece-kirmizi.gif",
		"**Yüzsüz adam** \n1990’lı yıllarda Kanada’nın Québec eyaletine epey uzak bir kasabada yaşıyorduk. Evimize en yakın ev, 3 km uzakta oturan komşularımıza aitti. O zamanlar ben 6, kardeşlerim ise 4 ve 2 yaşlarındaydı. Soğuk bir kış gecesinde, birbirimize sarılmış uyuyorduk. Sonra alt kattan gelen seslerle uyandık. Yabancı bir adamın sesiydi ve anlayamadığımız bir dilde kendi kendine konuşuyor gibiydi. Babam bize sesimizi çıkarmamamızı söyleyerek, tüfeğiyle aşağıya indi. Ayak sesleri merdivenleri gıcırdattıkça nefesim biraz daha hızlanıyor, aşağıdaki kişinin (büyük ihtimalle hırsızdı) babama zarar vermemesi için dua ediyordum. Aradan yarım saat geçtikten sonra, babam yüzü bembeyaz olmuş bir şekilde geri döndü. Ne olduğunu sorduğumuzda “sadece fare” deyip geçiştirse de yalan söylediğini anlamıştım. \nErtesi gün olduğunda annem ısrarlarıma dayanamayarak olanlarını anlattı. Babam aşağıya indiğinde salonun ortasında deli gibi volta atan bir adam varmış. Bir yandan hızlı hızlı adım atıyor bir yandan da kendi kendine konuşuyormuş. Babamın “iyi misin” sorusu karşısında, adam aniden durup başını ona doğru çevirmiş. Gördüğü manzara karşısında ne yapacağını bilemeyen babam, hemen geri dönüp ışıkları yakmış ama salona yeniden döndüğünde karşısında hiç kimse yokmuş. Saniyeler önce gördüğü yüzü olmayan adamın şokuyla da bize “sadece fare” diyerek, olanları anneme anlatmış. \nAnnem bu hikayeyi anlattıktan kısa süre sonra komşularımızdan biri geldi ve birlikte sohbet etmeye başladılar. Ve duyduklarım karşısında daha çok korkmaya başladım. Çünkü gelen kadın anneme, gece yaşanan kazadan haberimiz olup olmadığını sorduktan sonra, genç bir adamın yolda kaza yapıp kafasına saplanan ağaç dalı yüzünden feci şekilde öldüğünü anlattı. Kadın heyecanlı heyecanlı anlatmaya devam ederken, bizim annemle düşündüğümüz tek şey dün gece evimize gelen yüzsüz adamdı! https://img.paratic.com/dosya/2017/06/uzun-korku-hikayeleri-yuzsuz-adam.gif"
    ]
    var result = responses[Math.floor(Math.random(1) * responses.length)]
    return message.channel.send(result);
};

exports.conf = {
  enabled: true,
  guildOnly: false,
  aliases: [],
  permLevel: 0
};

exports.help = {
  name: 'korkuhikayeleri',
  description: 'Çok korkunç hikayeleri ile sizleri korkutabilir.',
  usage: 'korkuhikayeleri',
};
